version: '3.8'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5000"
  
  exam-type-service:
    build:
      context: ./exam-type-service
    ports:
      - "5002:5000"

  question-service:
    build:
      context: ./question-service
    ports:
      - "5003:5000"

  category-service:
    build:
      context: ./category-service
    ports:
      - "5004:5000"

  year-service:
    build:
      context: ./year-service
    ports:
      - "5005:5000"

  cart-service:
    build:
      context: ./cart-service
    ports:
      - "5006:5000"
